# Generated by Django 5.1.5 on 2025-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECU'), ('P', 'PR0FORMA FACTURE'), ('F', 'FACTURE')], max_length=1),
        ),
    ]
