# Generated by Django 5.1.5 on 2025-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PR0FORMA FACTURE'), ('I', 'INVOICE')], max_length=1),
        ),
    ]
