# Generated by Django 5.1.5 on 2025-05-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0004_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='fact_app.invoice'),
        ),
    ]
